# Generated by Django 5.2 on 2025-04-30 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textpost',
            name='slug',
        ),
    ]
