# Generated by Django 5.2 on 2025-05-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_alter_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['publish']},
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='blogs_comme_publish_a27466_idx',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['publish'], name='blogs_comme_publish_2019f7_idx'),
        ),
    ]
