# Generated by Django 5.2 on 2025-05-22 05:33

import django.utils.timezone
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoForGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, storage=storages.backends.s3.S3Storage(), upload_to='users/%Y/%m/%d/')),
                ('author', models.CharField(max_length=10)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.FileField(blank=True, storage=storages.backends.s3.S3Storage(), upload_to='users/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='textpost',
            name='image',
            field=models.FileField(blank=True, storage=storages.backends.s3.S3Storage(), upload_to='posts/%Y/%m/%d/'),
        ),
    ]
