# Generated by Django 5.2 on 2025-05-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_textpost_image_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpost',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='textpost',
            name='body',
            field=models.CharField(blank=True),
        ),
    ]
