# Generated by Django 5.2 on 2025-05-23 13:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import storages.backends.s3
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.FileField(blank=True, storage=storages.backends.s3.S3Storage(), upload_to='users/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='textpost',
            name='image',
            field=models.FileField(blank=True, storage=storages.backends.s3.S3Storage(), upload_to='posts/%Y/%m/%d/'),
        )
    ]
