# Generated by Django 5.2 on 2025-05-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-publish']},
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='blogs_comme_publish_2019f7_idx',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-publish'], name='blogs_comme_publish_a27466_idx'),
        ),
    ]
