# Generated by Django 5.2 on 2025-05-23 13:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import storages.backends.s3
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_alter_comment_author_alter_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoForGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='gallery/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'bmp'])])),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_from_gallery', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
