# Generated by Django 5.2 on 2025-05-23 18:41

import django.core.validators
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_photoforgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoforgallery',
            name='image',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='gallery/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'bmp', 'jpeg'])]),
        ),
    ]
