# Generated by Django 5.2 on 2025-05-22 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_photoforgallery_alter_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoforgallery',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_from_gallery', to=settings.AUTH_USER_MODEL),
        ),
    ]
