# Generated by Django 5.2 on 2025-06-03 17:28

import django.core.validators
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_alter_photoforgallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoforgallery',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.FileField(blank=True, storage=storages.backends.s3.S3Storage(), upload_to='users/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'bmp', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='photoforgallery',
            name='image',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='gallery/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'bmp', 'jpeg', 'mp4', 'mov', 'mkv', 'avi'])]),
        ),
    ]
