# Generated by Django 5.2 on 2025-05-22 16:46

import django.core.validators
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_alter_photoforgallery_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoforgallery',
            name='photo',
        ),
        migrations.AddField(
            model_name='photoforgallery',
            name='image',
            field=models.FileField(default=1, storage=storages.backends.s3.S3Storage(), upload_to='gallery/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'bmp'])]),
            preserve_default=False,
        ),
    ]
