# Generated by Django 5.2 on 2025-06-03 17:39

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_photoforgallery_thumbnail_alter_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoforgallery',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='thumbnails/%Y/%m/%d/'),
        ),
    ]
