# Generated by Django 5.2 on 2025-06-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_alter_photoforgallery_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoforgallery',
            name='thumbnail',
        ),
    ]
