# Generated by Django 5.2.3 on 2025-06-16 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_remove_photoforgallery_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photoforgallery',
            options={'ordering': ['-publish']},
        ),
        migrations.AddField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='photoforgallery',
            index=models.Index(fields=['-publish'], name='blogs_photo_publish_bc344f_idx'),
        ),
    ]
